# Generated by Django 5.1.3 on 2025-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
